replicaCount: 2
image:
  repository: yapedro/flask-crud
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  nodePort: 30081
env:
  DB_HOST: "crud-db-postgresql"
  DB_USER: "postgres"
  DB_PASS: "postgres"
  DB_NAME: "postgres"
  REDIS_HOST: "crud-db-redis-master"