apiVersion: v2
name: crud-db
version: 0.1.0
dependencies:
  - name: postgresql
    version: 15.2.5
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 19.0.1
    repository: https://charts.bitnami.com/bitnami