apiVersion: v2
name: crud-db
version: 0.1.0
dependencies:
  - name: postgresql
    version: 13.2.24
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 18.6.1
    repository: https://charts.bitnami.com/bitnami