apiVersion: v2
name: crud-db
version: 0.1.0
dependencies:
  - name: postgresql
    version: 18.4.1
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 25.3.2
    repository: https://charts.bitnami.com/bitnami