kube-prometheus-stack:
  grafana:
    adminPassword: admin
    service:
      type: NodePort
      nodePort: 8082
  prometheusOperator:
    admissionWebhooks:
      enabled: false
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false