kube-prometheus-stack:
  grafana:
    adminPassword: admin
  prometheusOperator:
    admissionWebhooks:
      enabled: false
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false