apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crud-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ya-Pedro/k3s.git'
    path: helm/db
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crud-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ya-Pedro/k3s.git'
    path: helm/app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crud-observability
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ya-Pedro/k3s.git'
    path: helm/observability
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true